// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace ELIS_MVC_CORE_WebAPI.Models
{
    public partial class CorsiContext : DbContext
    {
        public CorsiContext()
        {
        }

        public CorsiContext(DbContextOptions<CorsiContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Corsi> Corsis { get; set; }
        public virtual DbSet<Partecipanti> Partecipantis { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Corsi>(entity =>
            {
                entity.HasKey(e => e.Idcorso);

                entity.ToTable("Corsi");

                entity.Property(e => e.Idcorso)
                    .ValueGeneratedNever()
                    .HasColumnName("IDCorso");

                entity.Property(e => e.Costo).HasColumnType("money");

                entity.Property(e => e.Scaletta)
                    .HasMaxLength(250)
                    .IsUnicode(false);

                entity.Property(e => e.Titolo)
                    .HasMaxLength(100)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<Partecipanti>(entity =>
            {
                entity.HasKey(e => e.Idpartecipante);

                entity.ToTable("Partecipanti");

                entity.Property(e => e.Idpartecipante)
                    .ValueGeneratedNever()
                    .HasColumnName("IDPartecipante");

                entity.Property(e => e.Cognome)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.DataNascita).HasColumnType("date");

                entity.Property(e => e.Nome)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Residenza)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.TitoloStudio)
                    .HasMaxLength(100)
                    .IsUnicode(false);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}