// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ELIS_MVC_CORE_WebAPI.Models
{
    public partial class Corsi
    {
        public int Idcorso { get; set; }
        public string Titolo { get; set; }
        public int? Durata { get; set; }
        public string Scaletta { get; set; }
        public decimal? Costo { get; set; }
    }
}