// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ELIS_MVC_CORE_WebAPI.Models
{
    public partial class Partecipanti
    {
        public int Idpartecipante { get; set; }
        public string Nome { get; set; }
        public string Cognome { get; set; }
        public DateTime? DataNascita { get; set; }
        public string Residenza { get; set; }
        public string TitoloStudio { get; set; }
    }
}