// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ELIS_MVC_Core.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace ELIS_MVC_Core.Models
{
    public partial class CorsiContext
    {
        private ICorsiContextProcedures _procedures;

        public virtual ICorsiContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new CorsiContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public ICorsiContextProcedures GetProcedures()
        {
            return Procedures;
        }

        protected void OnModelCreatingGeneratedProcedures(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<usp_PartecipantiEdizioniResult>().HasNoKey().ToView(null);
        }
    }

    public partial class CorsiContextProcedures : ICorsiContextProcedures
    {
        private readonly CorsiContext _context;

        public CorsiContextProcedures(CorsiContext context)
        {
            _context = context;
        }

        public virtual async Task<List<usp_PartecipantiEdizioniResult>> usp_PartecipantiEdizioniAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<usp_PartecipantiEdizioniResult>("EXEC @returnValue = [dbo].[usp_PartecipantiEdizioni]", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
