// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace ELIS_MVC_Core.Models
{
    public partial class CorsiContext : DbContext
    {
        public CorsiContext()
        {
        }

        public CorsiContext(DbContextOptions<CorsiContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Corsi> Corsis { get; set; }
        public virtual DbSet<Edizioni> Edizionis { get; set; }
        public virtual DbSet<Partecipanti> Partecipantis { get; set; }
        public virtual DbSet<Partecipazioni> Partecipazionis { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Corsi>(entity =>
            {
                entity.HasKey(e => e.Idcorso);

                entity.ToTable("Corsi");

                entity.Property(e => e.Idcorso)
                    .ValueGeneratedNever()
                    .HasColumnName("IDCorso");

                entity.Property(e => e.Costo).HasColumnType("money");

                entity.Property(e => e.Scaletta)
                    .HasMaxLength(250)
                    .IsUnicode(false);

                entity.Property(e => e.Titolo)
                    .HasMaxLength(100)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<Edizioni>(entity =>
            {
                entity.HasKey(e => e.Idedizione);

                entity.ToTable("Edizioni");

                entity.Property(e => e.Idedizione)
                    .ValueGeneratedNever()
                    .HasColumnName("IDEdizione");

                entity.Property(e => e.DataInizio).HasColumnType("date");

                entity.Property(e => e.Idcorso).HasColumnName("IDCorso");

                entity.Property(e => e.Luogo)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.HasOne(d => d.IdcorsoNavigation)
                    .WithMany(p => p.Edizionis)
                    .HasForeignKey(d => d.Idcorso)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Corsi_Edizioni");
            });

            modelBuilder.Entity<Partecipanti>(entity =>
            {
                entity.HasKey(e => e.Idpartecipante);

                entity.ToTable("Partecipanti");

                entity.Property(e => e.Idpartecipante)
                    .ValueGeneratedNever()
                    .HasColumnName("IDPartecipante");

                entity.Property(e => e.Cognome)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.DataNascita).HasColumnType("date");

                entity.Property(e => e.Nome)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Residenza)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.TitoloStudio)
                    .HasMaxLength(100)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<Partecipazioni>(entity =>
            {
                entity.HasKey(e => e.IdPartecipazione)
                    .HasName("PK__Table__AC316B1E6FB32DF8");

                entity.ToTable("Partecipazioni");

                entity.Property(e => e.IdPartecipazione).ValueGeneratedNever();

                entity.Property(e => e.Giudizio)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Idedizione).HasColumnName("IDEdizione");

                entity.Property(e => e.Idpartecipante).HasColumnName("IDPartecipante");

                entity.HasOne(d => d.IdedizioneNavigation)
                    .WithMany(p => p.Partecipazionis)
                    .HasForeignKey(d => d.Idedizione)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Edizione_Partecipazione");

                entity.HasOne(d => d.IdpartecipanteNavigation)
                    .WithMany(p => p.Partecipazionis)
                    .HasForeignKey(d => d.Idpartecipante)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Partecipante_Partecipazione");
            });

            OnModelCreatingGeneratedProcedures(modelBuilder);
            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}