// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ELIS_MVC_Core.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace ELIS_MVC_Core.Models
{
    public partial interface ICorsiContextProcedures
    {
        Task<List<usp_PartecipantiEdizioniResult>> usp_PartecipantiEdizioniAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
