// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ELIS_MVC_Core.Models
{
    public partial class Partecipazioni
    {
        public int IdPartecipazione { get; set; }
        public int Idpartecipante { get; set; }
        public int Idedizione { get; set; }
        public string Giudizio { get; set; }

        public virtual Edizioni IdedizioneNavigation { get; set; }
        public virtual Partecipanti IdpartecipanteNavigation { get; set; }
    }
}