// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ELIS_MVC_Core.Models
{
    public partial class usp_PartecipantiEdizioniResult
    {
        public int IDEdizione { get; set; }
        public string Titolo { get; set; }
        public int? Num_Partecipanti { get; set; }
    }
}
